data:
  target_variable: "two_year_recid" # Your target column name
  sensitive_feature: "sex"          # Protected attribute column
  labels:
    favourable: 0    # no receid
    unfavourable: 1  # did receid
  protected_values:
    privileged: 1    # female
    unprivileged: 0  # male

model:
  hidden_layer_sizes: [50, 50]
  implies: "Godel"  # Options: KleeneDienes, Godel, Reichenbach, Goguen, Luk
  p_mean: 1
  aggregator_deviation: 2

fairness:
  enabled: true
  weight: 0.5

training:
  epochs: 200